title: 'Angular After Tutorial'
summary: 'この本ではAngularのチュートリアルを終えた人に向けて、コンポーネントやサービス、アプリケーション全体の設計を改善していく道筋を示します。この本はベストプラクティスの変化に合わせ、不定期にコンテンツをアップデートしていきます。'
topics: [angular, rxjs]
published: true
price: 0 # 有料の場合200〜5000
