title: "Angular After Tutorial"
summary: "この本ではAngularのチュートリアルを終えた人に向けて、コンポーネントやサービス、アプリケーション全体の設計を改善していく道筋を示します。"
topics: [angular]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 0-1-introduction
  - 1-1-first-refactoring
  - 1-2-separate-components
  - 1-3-creating-service
  - 1-4-forms-and-state
  - 1-5-routing
